### ISSUE TITLE
Hesitating on the way this is approached

### ISSUE THREAD

**Issue by Arteneko** [sneak/consoledonottrack.com#3]
Most cited tools are following an opt-out policy (much like VSCode, dotnet, etc.).

I feel that instead of adding a common opt-out lock, it should be an opt-in instead.

**Comment by dmbaturin** [comment]
I think the standard should provide both. If there are widely accepted ways to opt in and opt out, everyone if better off. Add variable like `TRACKING_CONSENT=1` that enables tracking for opt-in programs.

Also, my feeling is that the distinction should be made between _explicit_ and _implicit_ service requests, rather than essential and non-essential.

Explicit request is a request initiated by the user who's controlling what service will be contacted and what data will be sent, else it's implicit.

For example, typing a URL into a web browser address bar is an explicit request, so is `ssh root@server.example.com`—in both cases the user is fully aware what service it will connect to and can cancel the request before any connection is made.

Usage stats reporting, checking for updates are clearly implicit requests and the user should be able to disable them.

It gets more interesting with online service clients. If a program is a client for an online service that requires authentication, then read requests to that service it makes in the background are still explicitly authorized by the user who setup the login credentials.
Write requests are considered implicit unless the user has a chance to review the data and confirm the request.

However, clients for services that don't require authentication must request consent before making any requests. For a pathological example, suppose a user installs Password Strength Checker Ultimate Edition 2019. The user enters `pwstrengthcheck --password qwerty`. Unbestknown to the user, the program is a thin client for a remote server that sends a GET request to `https://api.example.com/pwcheck?pw=qwerty`. That is essential functionality for that program, but would any user like it to sends passwords like that without confirmation?

So, I think the standard guidelines should be:

* Software developers should provide accurate and complete information regarding tracking and implicit requests it makes.
* Programs *SHOULD* use an opt-in model for tracking (and all other implicit requests).
* Programs with opt-in tracking *MAY* enable tracking and implicit requests if `TRACKING_CONSENT=1`
* Programs *MUST* disable tracking and all implicit requests if `DO_NOT_TRACK=1` regardless of their tracking model (opt-in or opt-out).
* There *SHOULD* be granular settings for tracking and implicit requests.

**Comment by sneak** [comment]
> Most cited tools are following an opt-out policy (much like VSCode, dotnet, etc.).

> I feel that instead of adding a common opt-out lock, it should be an opt-in instead.

I agree.  Developers that want analytics, however, feel differently, because if they make it opt-in they get a lot less data.  They've ignored the viewpoint that phoning home without explicit opt-in consent is unethical.

This is not about "whether or not tracking should be opt in or opt out".  I personally believe that it should be opt in.  That is not the world we seem to be living in.

This is a unifying standard for *how* to opt out, for using software that demands one opt-out of tracking.
